app/models/__init__.py
from app import db
from werkzeug.security import check_password_hash
from flask_login import UserMixin


class User(db.Document, UserMixin):
    user_id = db.IntField(primary_key=True)
    first_name = db.StringField(max_length=50)
    last_name = db.StringField(max_length=50)
    email = db.StringField(max_length=50, unique=True)
    password = db.StringField()

    @staticmethod
    def match(email, password):
        user = User.objects.get(email=email)
        if user and check_password_hash(user.password, password):
            return user
        return None


class Course(db.Document):
    course_id = db.StringField(max_length=10, primary_key=True)
    title = db.StringField(max_length=100)
    description = db.StringField(max_length=255)
    credits = db.IntField()
    term = db.StringField(max_length=25)


class Enrollment(db.Document):
    user_id = db.ReferenceField(User)
    course_id = db.ReferenceField(Course)

app/models/populate.py
from . import Course, User
import mongoengine
import json
from werkzeug.security import generate_password_hash

DB_DATA_PATH = "static/models/"


def populate():
    populate_courses()
    populate_users()


def populate_courses():
    with open(f"{DB_DATA_PATH}/courses.json") as fp:
        for row in json.load(fp):
            try:
                Course(course_id=row['courseID'], title=row['title'], description=row['description'],
                       credits=row['credits'], term=row['term']).save()
            except mongoengine.errors.NotUniqueError:
                pass


def populate_users():
    with open(f"{DB_DATA_PATH}/users.json") as fp:
        for row in json.load(fp):
            try:
                User(user_id=row['id'], first_name=row['first_name'], last_name=row['last_name'],
                     email=row['email'], password=generate_password_hash(row['password'])).save()
            except mongoengine.errors.NotUniqueError:
                pass

app/forms.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, PasswordField, StringField
from wtforms.validators import DataRequired, Email, Length, EqualTo, ValidationError
from app.models import Enrollment, User


class LoginForm(FlaskForm):
    email = StringField("Email", validators=[DataRequired(), Email()])
    password = PasswordField("Password", validators=[
                             DataRequired(), Length(min=6, max=15)])
    remember_me = BooleanField("Remember Me")


class RegisterForm(FlaskForm):
    email = StringField("Email", validators=[DataRequired(), Email()])
    password = PasswordField("Password", validators=[
                             DataRequired(), Length(min=6, max=15)])
    password_confirm = PasswordField("Confirm Password", validators=[EqualTo('password'),
                                                                     DataRequired(), Length(min=6, max=15)])
    first_name = StringField("First Name", validators=[
                             DataRequired(), Length(min=2, max=20)])
    last_name = StringField("Last Name", validators=[
                            DataRequired(), Length(min=2, max=20)])

    def validate_email(self, email):
        if User.objects(email=email.data).first():
            raise ValidationError(f"{email.data} is already taken.")

app/__init__.py
from flask import Flask
from flask_mongoengine import MongoEngine
from flask_socketio import SocketIO
from flask_login import LoginManager
import os

db = MongoEngine()
socketio = SocketIO()
login_manager = LoginManager()


def create_app():
    app = Flask(__name__)
    from app.config import Config

    app.config.from_object(Config)

    db.init_app(app)
    socketio.init_app(app)
    login_manager.init_app(app)

    from app.models.populate import populate
    if bool(os.environ.get('POPULATE_DB')):
        populate()

    from app import user_handling

    from app import routes
    from app import api

    app.register_blueprint(routes.bp)
    app.register_blueprint(api.bp, url_prefix='/api')

    return app


if __name__ == '__main__':
    socketio.run(create_app())

app/routes.py
from flask import Blueprint, render_template, request, flash, url_for, redirect, session
from app.forms import LoginForm, RegisterForm
from app.models import Course, User, Enrollment
from werkzeug.security import generate_password_hash
from flask_login import login_user, login_required, logout_user, current_user


bp = Blueprint('routes', __name__)


@bp.route("/")
def index():
    return render_template("index.html")


@bp.route("/courses/", defaults={"term": "Spring 2019"})
@bp.route("/courses/<term>")
def courses(term):
    return render_template("courses.html", courses=Course.objects, term=term)


@bp.route("/register", methods=["GET", "POST"])
def register():
    if session.get('user_id'):
        flash(f"You are already logged in.", "success")
        return redirect(url_for('routes.index'))
    form = RegisterForm()
    if form.is_submitted():
        if form.validate():
            return handle_valid_user(form)
        else:
            return handle_form_error(form, 'routes.register')
    return render_template("register.html", form=form)


def handle_valid_user(form):
    user_id = User.objects().order_by("-user_id").limit(-1).first().user_id + 1
    User(user_id=user_id, first_name=form.first_name.data, last_name=form.last_name.data,
         email=form.email.data, password=generate_password_hash(form.password.data)).save()
    flash(
        f"You have successfully registered {form.first_name.data} user.", "success")
    return redirect(url_for('routes.index'))


@bp.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        flash(f"You are already logged in.", "success")
        return redirect(url_for('routes.index'))
    form = LoginForm()
    if form.is_submitted():
        if form.validate():
            return handle_user_match(User.match(form.email.data, form.password.data))
        else:
            return handle_form_error(form, 'routes.login')
    return render_template("login.html", form=form)


def handle_user_match(user):
    if user:
        flash(f"Hello {user.first_name}.", "success")
        login_user(user)
    else:
        flash("Email does not match password.", "danger")
    return redirect(url_for('routes.index'))


def handle_form_error(form, route):
    for field, error in form.errors.items():
        flash(f"{field}: {error[0]}", "danger")
    return redirect(url_for(route))


@bp.route("/logout")
@login_required
def logout():
    logout_user()
    flash(f"You are succesfully logged out.", "success")
    return redirect(url_for('routes.index'))


@bp.route("/enrollment", methods=["GET", "POST"])
@login_required
def enrollment():
    if request.method == "POST":
        return handle_enrollment_post()
    return handle_enrollment_get()


def handle_enrollment_post():
    course_id = request.form.get('course_id')
    user_id = current_user.user_id
    if course_id and user_id:
        if Enrollment.objects(course_id=course_id, user_id=user_id):
            flash(
                f"You are already enrolled for course {course_id}", "warning")
            return redirect(url_for('routes.courses'))
        else:
            Enrollment(course_id=course_id, user_id=user_id).save()
            flash(f"You have succesfully signed in for {course_id}", "success")
            return redirect(url_for('routes.enrollment'))


def handle_enrollment_get():
    user_id = current_user.user_id
    courses = Enrollment.objects.filter(
        user_id=user_id).order_by('course_id').values_list('course_id')
    user = User.objects.get(user_id=user_id)
    return render_template("enrollment.html", first_name=user.first_name, last_name=user.last_name, courses=courses)


@bp.route("/chat")
@login_required
def chat():
    return render_template("chat.html")

app/templates/chat.html
<script src="//cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.js"
    integrity="sha256-yr4fRk/GU1ehYJPAs8P4JlTgu0Hdsp4ZKrx8bDEDC3I=" crossorigin="anonymous"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/websocket.js') }}" defer></script>

{% extends "layout.html" %}

{% block content %}
<h1>Chat room</h1>
<h2>Hello {{ current_user.first_name }} {{ current_user.last_name }} </h2>
<div class="chat-container w-100 h-50 p-3" style="background-color: #eee;">
</div>

{% endblock %}

app/templates/courses.html
{% extends "layout.html" %}

{% block content %}
<h1>Course Offerings</h1>

<!--  Display the Term and Year here --->
<h3>Term: {{ term }}</h3>

<div>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Course ID</th>
                <th scope="col">Title</th>
                <th scope="col">Description</th>
                <th scope="col">Credits</th>
                <th scope="col">Term</th>
                <th scope="col">Enroll</th>
            </tr>
        </thead>
        <tbody>
            {% for course in courses %}
            <tr>
                <td scope='row'>{{ course.course_id }}</td>
                <td>{{ course.title }}</td>
                <td>{{ course.description }}</td>
                <td>{{ course.credits }}</td>
                <td>{{ course.term }}</td>
                <td>
                    <form action="{{ url_for('routes.enrollment') }}" method="POST">
                        <input type="hidden" name="course_id" value="{{ course.course_id }}">
                        <input type="hidden" name="title" value="{{ course.title }}">
                        <input type="hidden" name="term" value="{{ course.term }}">
                        <input type="submit" value="Enroll" class="btn btn-primary">
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

app/templates/enrollment.html
{% extends "layout.html" %}

{% block content %}
<div>
    <h4>{{ current_user.first_name }}'s {{ current_user.last_name }} courses:</h4>
    <br>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Course ID</th>
                <th scope="col">Title</th>
                <th scope="col">Credits</th>
                <th scope="col">Term</th>
            </tr>
        </thead>
        <tbody>
            {% for course in courses %}
            <tr>
                <td scope='row'>{{ course.course_id }}</td>
                <td>{{ course.title }}</td>
                <td>{{ course.credits }}</td>
                <td>{{ course.term }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

app/templates/includes/footer.html
<div class="container-fluid text-center bottom-container">
    <footer>
        <p>11.2020 Pawelek :)</p>
    </footer>
</div>

app/templates/includes/nav.html
<header>
    <nav>
        <ul class="nav nav-pills">
            <li class="nav-item"><a href="{{ url_for('routes.index') }}" class="nav-link">Home</a></li>
            <li class="nav-item"><a href="{{ url_for('routes.courses') }}" class="nav-link">Classes</a></li>
            <li class="nav-item"><a href="{{ url_for('routes.register') }}" class="nav-link">Register</a></li>
            {% if current_user.is_anonymous %}
            <li class="nav-item"><a href="{{ url_for('routes.login') }}" class="nav-link">Login</a></li>
            {% endif %}
            {% if current_user.is_authenticated %}
            <li class="nav-item"><a href="{{ url_for('routes.enrollment') }}" class="nav-link">Enrollment</a></li>
            <li class="nav-item"><a href="{{ url_for('routes.logout') }}" class="nav-link">Logout</a></li>
            <li class="nav-item"><a href="{{ url_for('routes.chat') }}" class="nav-link">Chat</a></li>
            {% endif %}
            <li class="nav-item"><a href="{{ url_for('api.users') }}" class="nav-link">Api Users</a></li>
            <li class="nav-item"><a href="{{ url_for('api.courses') }}" class="nav-link">Api Courses</a></li>
        </ul>
    </nav>
    <hr style="clear:both">
</header>

app/templates/index.html
{% extends "layout.html" %}

{% block content %}
<div class="row">
    <div class="col-md-12 text-center">
        <h1>Welcome to Pawelek's self study project :)</h1>

        {% if not session.user_id %}
        <p>Already registered? <a href="{{url_for('routes.login') }}">Login</a></p>
        {% endif %}

        <img src="{{ url_for('static', filename='images/cat.jpg') }}">

    </div>
</div>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html>

<head>
    <title>Pawelek's page</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" />
    <script type="text/javascript" src="{{ url_for('static', filename='js/script.js') }}" defer></script>
    <meta name="template" content="{{ self._TemplateReference__context.name }}">
</head>

<body>
    <div class="container">
        {% include "includes/nav.html" %}
        {% for category, message in get_flashed_messages(with_categories=true) %}
        <div class="alert alert-{{ category }}" role="alert">
            <p> {{ message }}</p>
        </div>
        {% endfor %}
        {% block content %}
        {% endblock %}
    </div>
    {% include "includes/footer.html" %}
</body>

</html>

app/templates/login.html
{% extends "layout.html" %}

{% block content %}
<h1>Login</h1>

<div class="row">
    <div class="col-md-6 offset-md-3">
        <form name="login" action="{{ url_for('routes.login') }}" method="POST">
            <div class="form-field">{{ form.hidden_tag() }}</div>
            <div class="form-field">{{ form.email.label }} {{ form.email(size=20) }}</div>
            <div class="form-field">{{ form.password.label }} {{ form.password }}</div>
            <input type="submit" value="Login" class="btn-submit btn-primary">
        </form>
    </div>
</div>
{% endblock %}

app/templates/register.html
{% extends "layout.html" %}

{% block content %}
<h2>New User Registration</h2>

<div class="row">
    <div class="col-md-6 offset-md-3">
        <div class="container">
            <form name="register" action="{{ url_for('routes.register') }}" method="POST">
                <div class="form-field">{{ form.hidden_tag() }}</div>
                <div class="form-field">{{ form.email.label }} {{ form.email(size=20) }}</div>
                <div class="form-field">{{ form.password.label }} {{ form.password }}</div>
                <div class="form-field">{{ form.password_confirm.label }} {{ form.password_confirm }}</div>
                <div class="form-field">{{ form.first_name.label }} {{ form.first_name }}</div>
                <div class="form-field">{{ form.last_name.label }} {{ form.last_name }}</div>
                <input type="submit" value="Register" class="btn-submit btn-primary">
            </form>
        </div>
    </div>
</div>
{% endblock %}